### ISSUE TITLE
Call to member function get_stylesheet() on null

### ISSUE THREAD

**Issue by dev-ns8** [wpovernight/wcpdf-dompdf-0.8.3#1]
Hello,

All of a sudden this plugin on a friend of mines site is throwing this error.  

It seems the `$frame->get_style()` is not returning the expected object anymore? I have attached the full stack-trace below 

`
Fatal error: Call to a member function get_stylesheet() on null

/home/dobberspasties/public_html/wp-content/plugins/wcpdf-dompdf-0.8.3/vendor/dompdf/dompdf/src/FrameReflower/Page.php (53)

#0 /home/dobberspasties/public_html/wp-content/plugins/wcpdf-dompdf-0.8.3/vendor/dompdf/dompdf/src/FrameReflower/Page.php(102): Dompdf\FrameReflower\Page->apply_page_style(Object(Dompdf\FrameDecorator\Page), 1)
#1 /home/dobberspasties/public_html/wp-content/plugins/wcpdf-dompdf-0.8.3/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\Page->reflow(NULL)
#2 /home/dobberspasties/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Dompdf.php(765): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#3 /home/dobberspasties/public_html/wp-content/plugins/wcpdf-dompdf-0.8.3/woocommerce-pdf-ips-dompdf-0.8.3.php(59): Dompdf\Dompdf->render()
#4 /home/dobberspasties/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document.php(835): WCPDF_Custom_PDF_Maker_dompdf_0_8_3->output()
#5 /home/dobberspasties/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document.php(901): WPO\WC\PDF_Invoices\Documents\Order_Document->get_pdf()
#6 /home/dobberspasties/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-main.php(466): WPO\WC\PDF_Invoices\Documents\Order_Document->output_pdf('download')
#7 /home/dobberspasties/public_html/wp-includes/class-wp-hook.php(303): WPO\WC\PDF_Invoices\Main->generate_pdf_ajax('')
#8 /home/dobberspasties/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#9 /home/dobberspasties/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#10 /home/dobberspasties/public_html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_generat...')
#11 {main}
`

**Comment by alexmigf** [comment]
Is there a special reason for you to be using a dated DOMPDF version?

**Comment by dev-ns8** [comment]
Thanks for the timely reply Alex!

No specific reason.  This is just what my friend had on his site.  He is not very tech literate and thus asked if I could take a look.  I am not super experienced with Wordpress, but do you suggest I upgrade DOMPDF version? From what I can see on my friends server, he doesn't use composer to manage his Wordpress plugins, so should I just plop the source from https://github.com/dompdf/dompdf into his plugins directory?

**Comment by alexmigf** [comment]
No. First check the server PHP version please. If it's 7.1 or higher you can delete that extension because the [free PDF plugin runs the latest DOMPDF version](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/31d33bf49788cf06fe9e6d4cf93f1ebf2ecddeab/composer.json#L12).

Documentation page: https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/backwards-compatibility-with-php-5-6/

**Comment by dev-ns8** [comment]
Appreciate it Alex! That was the solution I needed.  All is working now.  Thanks a lot.
